### ISSUE TITLE
Daemon Bride Additional Gains 2020 is not working 

### ISSUE THREAD

**Issue by Bunny-Head** [Hipnosis183/XB-Monitor#1]
Hello,

When I put XBMonitor on the game's directory it doesn't works. I rename the game's .exe to game.exe and it "blinks" for a second and then it crash.

Any chances to see this fixed?

Thank you!

**Comment by Hipnosis183** [comment]
Hey, glad to see someone using this thing.

Sadly, Additional Gains is not an eX-BOARD game, but a re-release on Taito's NESiCAxLive service, which runs on Type X hardware series. You will need to use an emulator which supports Nesica emulation, like JConfig or TeknoParrot, as my other project, TTX-Monitor, only implements the I/O board emulation.

XB-Monitor will work as expected with the original release, but for this one you should look somewhere else.

**Comment by Bunny-Head** [comment]
Thank you so much for the clarification Hipnosis183! My fault that I didn't check it before posting here and assume that it was the same board, my bad!

**Comment by Hipnosis183** [comment]
All good, it's easy to get confused with so many boards and services going on.
